paths:
  data_path: 'data'
  raw_data: 'raw_data'
  data_version: 'data_versions'
  processed_data: 'processed_data'
  notebook_path: 'notebooks'

data:
  category_features: ["age"]
  numerical_features: ['gender', 'annual_income', 'spending_score']

feature_engineering:
  imputation:
    numerical: 'SimpleImputer'
    categorical: 'SimpleImputer'
  outlier_handling:
    method: 'winsorization'
    threshold: 0.01

  

